export const birthAugers = {
	1: { number: 1, auger: 'Harsh winter: All attack rolls' },
	2: { number: 2, auger: 'The bull: Melee attack rolls' },
	3: { number: 3, auger: 'Fortunate date: Missile fire attack rolls' },
	4: { number: 4, auger: 'Raised by wolves: Unarmed attack rolls' },
	5: { number: 5, auger: 'Conceived on horseback: Mounted attack rolls' },
	6: { number: 6, auger: 'Born on the battlefield: Damage rolls' },
	7: { number: 7, auger: 'Wath of the bear: Melee damage rolls' },
	8: { number: 8, auger: 'Hawkeye: Missile fire damage rolls' },
	9: { number: 9, auger: 'Pack hunter: Attack and damage rolls for 0-level starting weapon' },
	10: { number: 10, auger: 'Born under the loom: Skill checks (including thief skills' },
	11: { number: 11, auger: "Fox's cunning: Find/disable traps" },
	12: { number: 12, auger: 'Four-leafed clover: Find secret doors' },
	13: { number: 13, auger: 'Seventh son: Spell checks' },
	14: { number: 14, auger: 'The raging storm: Spell damage' },
	15: { number: 15, auger: 'Righteous heart: Turn unholy checks' },
	16: { number: 16, auger: 'Survived the plague: Magical healing*' },
	17: { number: 17, auger: 'Lucky sign: Saving throws' },
	18: { number: 18, auger: 'Guardian angel: Savings throws to escape traps' },
	19: { number: 19, auger: 'Survived a spider bite: Saving throws against poison' },
	20: { number: 20, auger: 'Struck by lightning: Reflex saving throws' },
	21: { number: 21, auger: 'Lived through famine: Fortitude saving throws' },
	22: { number: 22, auger: 'Resisted temptation: Willpower saving throws' },
	23: { number: 23, auger: 'Charmed house: Armor Class' },
	24: { number: 24, auger: 'Speed of the cobra: Initiative' },
	25: { number: 25, auger: 'Bountiful harvest: Hit points (applies at each level' },
	26: { number: 26, auger: "Warrior's arm: Critical hit tables**" },
	27: { number: 27, auger: 'Unholy house: Corruption rolls' },
	28: { number: 28, auger: 'The Broken Star: Fumbles**' },
	29: { number: 29, auger: 'Birdsong: Number of languages' },
	30: { number: 30, auger: "Wild child: Speed (each +1/-1 = +5'/-5' speed" }
};
