export const birthAugers = {
	1: { key: 1, auger: 'Harsh winter: All attack rolls' },
	2: { key: 2, auger: 'The bull: Melee attack rolls' },
	3: { key: 3, auger: 'Fortunate date: Missile fire attack rolls' },
	4: { key: 4, auger: 'Raised by wolves: Unarmed attack rolls' },
	5: { key: 5, auger: 'Conceived on horseback: Mounted attack rolls' },
	6: { key: 6, auger: 'Born on the battlefield: Damage rolls' },
	7: { key: 7, auger: 'Wath of the bear: Melee damage rolls' },
	8: { key: 8, auger: 'Hawkeye: Missile fire damage rolls' },
	9: { key: 9, auger: 'Pack hunter: Attack and damage rolls for 0-level starting weapon' },
	10: { key: 10, auger: 'Born under the loom: Skill checks (including thief skills' },
	11: { key: 11, auger: "Fox's cunning: Find/disable traps" },
	12: { key: 12, auger: 'Four-leafed clover: Find secret doors' },
	13: { key: 13, auger: 'Seventh son: Spell checks' },
	14: { key: 14, auger: 'The raging storm: Spell damage' },
	15: { key: 15, auger: 'Righteous heart: Turn unholy checks' },
	16: { key: 16, auger: 'Survived the plague: Magical healing*' },
	17: { key: 17, auger: 'Lucky sign: Saving throws' },
	18: { key: 18, auger: 'Guardian angel: Savings throws to escape traps' },
	19: { key: 19, auger: 'Survived a spider bite: Saving throws against poison' },
	20: { key: 20, auger: 'Struck by lightning: Reflex saving throws' },
	21: { key: 21, auger: 'Lived through famine: Fortitude saving throws' },
	22: { key: 22, auger: 'Resisted temptation: Willpower saving throws' },
	23: { key: 23, auger: 'Charmed house: Armor Class' },
	24: { key: 24, auger: 'Speed of the cobra: Initiative' },
	25: { key: 25, auger: 'Bountiful harvest: Hit points (applies at each level' },
	26: { key: 26, auger: "Warrior's arm: Critical hit tables**" },
	27: { key: 27, auger: 'Unholy house: Corruption rolls' },
	28: { key: 28, auger: 'The Broken Star: Fumbles**' },
	29: { key: 29, auger: 'Birdsong: key of languages' },
	30: { key: 30, auger: "Wild child: Speed (each +1/-1 = +5'/-5' speed" }
};
