export const characterNames = {
	Elf: [
		{ name: 'Aelrindel' },
		{ name: 'Elendil' },
		{ name: 'Galadriel' },
		{ name: 'Lorindol' },
		{ name: 'Thranduil' },
		{ name: 'Celeborn' },
		{ name: 'Eowyn' },
		{ name: 'Legolas' },
		{ name: 'Arwen' },
		{ name: 'Glorfindel' },
		{ name: 'Haldir' },
		{ name: 'Faelwen' },
		{ name: 'Eldarion' },
		{ name: 'Nimrodel' },
		{ name: 'Finrod' },
		{ name: 'Aranel' },
		{ name: 'Eldamar' },
		{ name: 'Luthien' },
		{ name: 'Earendil' },
		{ name: 'Gil-galad' }
	],
	Dwarf: [
		{ name: 'Thorin' },
		{ name: 'Gimli' },
		{ name: 'Dwalin' },
		{ name: 'Balin' },
		{ name: 'Fili' },
		{ name: 'Kili' },
		{ name: 'Oin' },
		{ name: 'Gloin' },
		{ name: 'Bifur' },
		{ name: 'Bofur' },
		{ name: 'Bombur' },
		{ name: 'Dori' },
		{ name: 'Nori' },
		{ name: 'Ori' },
		{ name: 'Durin' },
		{ name: 'Thrain' },
		{ name: 'Thror' },
		{ name: 'Dain' },
		{ name: 'Gundren' },
		{ name: 'Nain' }
	],
	Halfling: [
		{ name: 'Bilbo' },
		{ name: 'Frodo' },
		{ name: 'Samwise' },
		{ name: 'Merry' },
		{ name: 'Pippin' },
		{ name: 'Rosie' },
		{ name: 'Daisy' },
		{ name: 'Ruby' },
		{ name: 'Lily' },
		{ name: 'Poppy' },
		{ name: 'Daisy' },
		{ name: 'Milo' },
		{ name: 'Oliver' },
		{ name: 'Charlie' },
		{ name: 'Jack' },
		{ name: 'Henry' },
		{ name: 'Leo' },
		{ name: 'Theo' },
		{ name: 'Archie' },
		{ name: 'Oscar' }
	],
	Human: [
		{ name: 'William' },
		{ name: 'Richard' },
		{ name: 'John' },
		{ name: 'Henry' },
		{ name: 'Edward' },
		{ name: 'Robert' },
		{ name: 'Thomas' },
		{ name: 'Arthur' },
		{ name: 'James' },
		{ name: 'Philip' },
		{ name: 'Charles' },
		{ name: 'George' },
		{ name: 'Louis' },
		{ name: 'Francis' },
		{ name: 'Peter' },
		{ name: 'Stephen' },
		{ name: 'David' },
		{ name: 'Alexander' },
		{ name: 'Roger' },
		{ name: 'Nicholas' }
	]
};
